apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    component: "server"
    app: kubecost-prometheus-server
    release: kubecost
    chart: prometheus-11.0.2
    heritage: Helm
  name: kubecost-prometheus-server
  namespace: kubecost
spec:
 # storageClassName: gp2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "32Gi"
  volumeName: gp2-prom